import { Metadata } from "next";
import { ArrowLeft, FileText, Scale, Gavel, ShieldAlert } from "lucide-react";
import Link from "next/link";
import Footer from "@/components/Footer";

export const metadata: Metadata = {
  title: "Terms of Service | BioVibes Terms & Conditions",
  description: "Read the official terms and conditions for using BioVibes AI services. Learn about our content usage and user agreements.",
  alternates: {
    canonical: '/terms',
  },
};

export default function TermsPage() {
  return (
    <div className="min-h-screen bg-background text-foreground flex flex-col font-sans">
      <header className="w-full flex justify-between items-center py-6 px-6 md:px-12 border-b border-panel-border bg-background/80 backdrop-blur-md sticky top-0 z-50">
        <div className="flex items-center gap-4">
          <Link href="/" className="p-2 hover:bg-white/10 rounded-full transition-colors">
            <ArrowLeft className="w-5 h-5 text-neon-blue" />
          </Link>
          <h1 className="text-2xl md:text-3xl font-extrabold tracking-tight text-transparent bg-clip-text bg-gradient-to-r from-neon-purple to-neon-blue">
            BioVibes
          </h1>
        </div>
      </header>

      <main className="flex-1 max-w-4xl mx-auto px-6 py-16">
        <div className="mb-12 flex items-center gap-3">
          <FileText className="w-10 h-10 text-neon-purple" />
          <h2 className="text-4xl font-black text-white">Terms of Service</h2>
        </div>

        <div className="space-y-12 text-foreground/70 leading-relaxed text-sm md:text-base">
          <section className="space-y-4">
            <h3 className="text-xl font-bold text-white flex items-center gap-2">
              <Scale className="w-5 h-5 text-neon-blue" /> 1. Acceptance of Terms
            </h3>
            <p>
              By using BioVibes.net, you agree to use our AI-generated content for lawful social media purposes. We do not store personal data generated during the bio creation process unless you choose to save it to our public gallery.
            </p>
          </section>

          <section className="space-y-4">
            <h3 className="text-xl font-bold text-white flex items-center gap-2">
              <Gavel className="w-5 h-5 text-neon-blue" /> 2. Content Usage
            </h3>
            <p>
              The content generated by BioVibes AI is intended for personal and commercial social media use. While we strive for high quality, we do not guarantee the uniqueness of the generated bios, as common themes may recur due to the nature of AI.
            </p>
          </section>

          <section className="space-y-4">
            <h3 className="text-xl font-bold text-white flex items-center gap-2">
              <ShieldAlert className="w-5 h-5 text-neon-blue" /> 3. Data Storage
            </h3>
            <p>
              Your inputs (role, vibe, keywords) are used solely to generate content. We do not permanently store these inputs unless the result is saved to the public gallery. You remain solely responsible for any content you choose to publish or save.
            </p>
          </section>

          <section className="pt-8 border-t border-panel-border/30">
            <p>Last Updated: {new Date().toLocaleDateString()}</p>
          </section>
        </div>
      </main>

      <Footer />
    </div>
  );
}
